game:
  port: 8765
  ip: 127.0.0.1
  CrashSpeed: 0.00006
  TakingBetTime: 20
  OverSessionWaitTime: 5


redis:
  host: 167.86.97.76
  port: 6379
  db: 0
  password: d3786d3dbb2d213ed40995d3d431888edc2895f992e20e45fda9f30b7238c083

mysql:
  host: 173.249.0.254
  user: root
  password: N54RMTD8qcJkHzX9
  database: aced

mongodb:
  host: 173.249.0.254
  user: axHfNV4YQEFv3qdQ
  password: BBHxhQK89nGUJCj9hmkPL5rzTFVX9qeh
  database: crash

rabbitmq:
  host: 167.86.97.76
  vhost: "/"
  user: admin
  password: StrongPassword

